services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules  
    working_dir: /app
    command: npm run dev
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3001

  backend:
    build: ./back
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres@db:5432/app-turnos-medicos
      PORT: 3001
    command: npm run start:dev

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app-turnos-medicos
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: